---
- hosts: 127.0.0.1
  connection: local

  tasks:

  - name: To start a telemetry collector
    script: /usr/bin/docker run -itd --name telemetry  -v /home/tesuto/code-samples/telemetry/telemetry.py:/root/telemetry.py akshshar/nanog75-telemetry  /bin/bash -c "python3 /root/telemetry.py"
    register: output

